import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FooterWrapper } from "@/common/Footer/FooterWrapper";
import QueryProvider from "@/provider/QueryProvider";
import { HeaderWrapper } from "@/common/Header/HeaderWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <div className="relative w-[375px] h-screen bg-[#F5F5F5] bg-image">
            <div className="relative z-10 w-full h-full flex flex-col items-center overflow-hidden">
              <HeaderWrapper />
              {children}
              <FooterWrapper />
            </div>
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
